load("@rules_python//python:defs.bzl", "py_test")

py_test(
    name = "observation_test",
    srcs = ["observation_test.py"],
    deps = [
        "//compiler_gym/service/proto",
        "//compiler_gym/views",
    ],
)