load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "spaces",
    srcs = [
        "__init__.py",
    ],
    deps = [":scalar"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "scalar",
    srcs = ["scalar.py"],
)