load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "service",
    srcs = ["__init__.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//kernel_gym/service/proto",
    ],
)